version: '3.8'

services:
  django:
    build:
      context: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  nodejs:
    build:
      context: ./nodejs
    ports:
      - "3000:3000"
  db:
    image: postgres:13
    environment:
      POSTGRES_NAME: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
      - nodejs
  flask_app:
    build: ./flask_app
    ports:
      - "5001:5001"
    volumes:
      - ./flask_app:/app
